apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
  - image: tonky.dev/api-gateway
    context: ./api-gateway/
  - image: tonky.dev/store
    context: ./store/
  - image: tonky.dev/cart
    context: ./cart/
deploy:
  kubectl:
    manifests:
    - ./api-gateway/k8s-service.yaml
    - ./store/k8s-service.yaml
    - ./jaeger-all-in-one-template.yaml
    - ./cart/k8s-service.yaml
portForward:
- resourceType: deployment
  resourceName: api-gateway
  port: 8080
  localPort: 9000
- resourceType: service
  resourceName: jaeger-query
  port: 80
  localPort: 9001
