apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: store
  labels:
    app: store
spec:
  selector:
    matchLabels:
      app: store
  replicas: 1
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: tonky.dev/store:latest  # or just image: redis
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: store-service
spec:
  selector:
    app: store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
